tracer:
  property:
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: "postgres"
    url: "jdbc:/postgresql://postgresql:12345@localhost:5432/spring"
    username: "postgres"
    password: "12345"
    testWhileIdle: true
    validationQuery: "SELECT 1"




